// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: raft_internal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Etcdserverpb {

  /// <summary>Holder for reflection information generated from raft_internal.proto</summary>
  public static partial class RaftInternalReflection {

    #region Descriptor
    /// <summary>File descriptor for raft_internal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RaftInternalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNyYWZ0X2ludGVybmFsLnByb3RvEgxldGNkc2VydmVycGIaCmdvZ28ucHJv",
            "dG8aEGV0Y2RzZXJ2ZXIucHJvdG8aCXJwYy5wcm90byJECg1SZXF1ZXN0SGVh",
            "ZGVyEgoKAklEGAEgASgEEhAKCHVzZXJuYW1lGAIgASgJEhUKDWF1dGhfcmV2",
            "aXNpb24YAyABKAQiywwKE0ludGVybmFsUmFmdFJlcXVlc3QSKwoGaGVhZGVy",
            "GGQgASgLMhsuZXRjZHNlcnZlcnBiLlJlcXVlc3RIZWFkZXISCgoCSUQYASAB",
            "KAQSIQoCdjIYAiABKAsyFS5ldGNkc2VydmVycGIuUmVxdWVzdBIpCgVyYW5n",
            "ZRgDIAEoCzIaLmV0Y2RzZXJ2ZXJwYi5SYW5nZVJlcXVlc3QSJQoDcHV0GAQg",
            "ASgLMhguZXRjZHNlcnZlcnBiLlB1dFJlcXVlc3QSNgoMZGVsZXRlX3Jhbmdl",
            "GAUgASgLMiAuZXRjZHNlcnZlcnBiLkRlbGV0ZVJhbmdlUmVxdWVzdBIlCgN0",
            "eG4YBiABKAsyGC5ldGNkc2VydmVycGIuVHhuUmVxdWVzdBIzCgpjb21wYWN0",
            "aW9uGAcgASgLMh8uZXRjZHNlcnZlcnBiLkNvbXBhY3Rpb25SZXF1ZXN0EjQK",
            "C2xlYXNlX2dyYW50GAggASgLMh8uZXRjZHNlcnZlcnBiLkxlYXNlR3JhbnRS",
            "ZXF1ZXN0EjYKDGxlYXNlX3Jldm9rZRgJIAEoCzIgLmV0Y2RzZXJ2ZXJwYi5M",
            "ZWFzZVJldm9rZVJlcXVlc3QSKQoFYWxhcm0YCiABKAsyGi5ldGNkc2VydmVy",
            "cGIuQWxhcm1SZXF1ZXN0Ej4KEGxlYXNlX2NoZWNrcG9pbnQYCyABKAsyJC5l",
            "dGNkc2VydmVycGIuTGVhc2VDaGVja3BvaW50UmVxdWVzdBI1CgthdXRoX2Vu",
            "YWJsZRjoByABKAsyHy5ldGNkc2VydmVycGIuQXV0aEVuYWJsZVJlcXVlc3QS",
            "NwoMYXV0aF9kaXNhYmxlGPMHIAEoCzIgLmV0Y2RzZXJ2ZXJwYi5BdXRoRGlz",
            "YWJsZVJlcXVlc3QSQAoMYXV0aGVudGljYXRlGPQHIAEoCzIpLmV0Y2RzZXJ2",
            "ZXJwYi5JbnRlcm5hbEF1dGhlbnRpY2F0ZVJlcXVlc3QSOAoNYXV0aF91c2Vy",
            "X2FkZBjMCCABKAsyIC5ldGNkc2VydmVycGIuQXV0aFVzZXJBZGRSZXF1ZXN0",
            "Ej4KEGF1dGhfdXNlcl9kZWxldGUYzQggASgLMiMuZXRjZHNlcnZlcnBiLkF1",
            "dGhVc2VyRGVsZXRlUmVxdWVzdBI4Cg1hdXRoX3VzZXJfZ2V0GM4IIAEoCzIg",
            "LmV0Y2RzZXJ2ZXJwYi5BdXRoVXNlckdldFJlcXVlc3QSTwoZYXV0aF91c2Vy",
            "X2NoYW5nZV9wYXNzd29yZBjPCCABKAsyKy5ldGNkc2VydmVycGIuQXV0aFVz",
            "ZXJDaGFuZ2VQYXNzd29yZFJlcXVlc3QSRQoUYXV0aF91c2VyX2dyYW50X3Jv",
            "bGUY0AggASgLMiYuZXRjZHNlcnZlcnBiLkF1dGhVc2VyR3JhbnRSb2xlUmVx",
            "dWVzdBJHChVhdXRoX3VzZXJfcmV2b2tlX3JvbGUY0QggASgLMicuZXRjZHNl",
            "cnZlcnBiLkF1dGhVc2VyUmV2b2tlUm9sZVJlcXVlc3QSOgoOYXV0aF91c2Vy",
            "X2xpc3QY0gggASgLMiEuZXRjZHNlcnZlcnBiLkF1dGhVc2VyTGlzdFJlcXVl",
            "c3QSOgoOYXV0aF9yb2xlX2xpc3QY0wggASgLMiEuZXRjZHNlcnZlcnBiLkF1",
            "dGhSb2xlTGlzdFJlcXVlc3QSOAoNYXV0aF9yb2xlX2FkZBiwCSABKAsyIC5l",
            "dGNkc2VydmVycGIuQXV0aFJvbGVBZGRSZXF1ZXN0Ej4KEGF1dGhfcm9sZV9k",
            "ZWxldGUYsQkgASgLMiMuZXRjZHNlcnZlcnBiLkF1dGhSb2xlRGVsZXRlUmVx",
            "dWVzdBI4Cg1hdXRoX3JvbGVfZ2V0GLIJIAEoCzIgLmV0Y2RzZXJ2ZXJwYi5B",
            "dXRoUm9sZUdldFJlcXVlc3QSUQoaYXV0aF9yb2xlX2dyYW50X3Blcm1pc3Np",
            "b24YswkgASgLMiwuZXRjZHNlcnZlcnBiLkF1dGhSb2xlR3JhbnRQZXJtaXNz",
            "aW9uUmVxdWVzdBJTChthdXRoX3JvbGVfcmV2b2tlX3Blcm1pc3Npb24YtAkg",
            "ASgLMi0uZXRjZHNlcnZlcnBiLkF1dGhSb2xlUmV2b2tlUGVybWlzc2lvblJl",
            "cXVlc3QiDwoNRW1wdHlSZXNwb25zZSJTChtJbnRlcm5hbEF1dGhlbnRpY2F0",
            "ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRIUCgxz",
            "aW1wbGVfdG9rZW4YAyABKAlCEMjiHgHg4h4B0OIeAcjhHgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gogoproto.GogoReflection.Descriptor, global::Etcdserverpb.EtcdserverReflection.Descriptor, global::Etcdserverpb.RpcReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Etcdserverpb.RequestHeader), global::Etcdserverpb.RequestHeader.Parser, new[]{ "ID", "Username", "AuthRevision" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etcdserverpb.InternalRaftRequest), global::Etcdserverpb.InternalRaftRequest.Parser, new[]{ "Header", "ID", "V2", "Range", "Put", "DeleteRange", "Txn", "Compaction", "LeaseGrant", "LeaseRevoke", "Alarm", "LeaseCheckpoint", "AuthEnable", "AuthDisable", "Authenticate", "AuthUserAdd", "AuthUserDelete", "AuthUserGet", "AuthUserChangePassword", "AuthUserGrantRole", "AuthUserRevokeRole", "AuthUserList", "AuthRoleList", "AuthRoleAdd", "AuthRoleDelete", "AuthRoleGet", "AuthRoleGrantPermission", "AuthRoleRevokePermission" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etcdserverpb.EmptyResponse), global::Etcdserverpb.EmptyResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etcdserverpb.InternalAuthenticateRequest), global::Etcdserverpb.InternalAuthenticateRequest.Parser, new[]{ "Name", "Password", "SimpleToken" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RequestHeader : pb::IMessage<RequestHeader> {
    private static readonly pb::MessageParser<RequestHeader> _parser = new pb::MessageParser<RequestHeader>(() => new RequestHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etcdserverpb.RaftInternalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeader(RequestHeader other) : this() {
      iD_ = other.iD_;
      username_ = other.username_;
      authRevision_ = other.authRevision_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeader Clone() {
      return new RequestHeader(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private ulong iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    /// <summary>
    /// username is a username that is associated with an auth token of gRPC connection
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auth_revision" field.</summary>
    public const int AuthRevisionFieldNumber = 3;
    private ulong authRevision_;
    /// <summary>
    /// auth_revision is a revision number of auth.authStore. It is not related to mvcc
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong AuthRevision {
      get { return authRevision_; }
      set {
        authRevision_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (Username != other.Username) return false;
      if (AuthRevision != other.AuthRevision) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0UL) hash ^= ID.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (AuthRevision != 0UL) hash ^= AuthRevision.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ID);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (AuthRevision != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(AuthRevision);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ID);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (AuthRevision != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AuthRevision);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestHeader other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0UL) {
        ID = other.ID;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.AuthRevision != 0UL) {
        AuthRevision = other.AuthRevision;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadUInt64();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 24: {
            AuthRevision = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// An InternalRaftRequest is the union of all requests which can be
  /// sent via raft.
  /// </summary>
  public sealed partial class InternalRaftRequest : pb::IMessage<InternalRaftRequest> {
    private static readonly pb::MessageParser<InternalRaftRequest> _parser = new pb::MessageParser<InternalRaftRequest>(() => new InternalRaftRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InternalRaftRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etcdserverpb.RaftInternalReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InternalRaftRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InternalRaftRequest(InternalRaftRequest other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      iD_ = other.iD_;
      v2_ = other.v2_ != null ? other.v2_.Clone() : null;
      range_ = other.range_ != null ? other.range_.Clone() : null;
      put_ = other.put_ != null ? other.put_.Clone() : null;
      deleteRange_ = other.deleteRange_ != null ? other.deleteRange_.Clone() : null;
      txn_ = other.txn_ != null ? other.txn_.Clone() : null;
      compaction_ = other.compaction_ != null ? other.compaction_.Clone() : null;
      leaseGrant_ = other.leaseGrant_ != null ? other.leaseGrant_.Clone() : null;
      leaseRevoke_ = other.leaseRevoke_ != null ? other.leaseRevoke_.Clone() : null;
      alarm_ = other.alarm_ != null ? other.alarm_.Clone() : null;
      leaseCheckpoint_ = other.leaseCheckpoint_ != null ? other.leaseCheckpoint_.Clone() : null;
      authEnable_ = other.authEnable_ != null ? other.authEnable_.Clone() : null;
      authDisable_ = other.authDisable_ != null ? other.authDisable_.Clone() : null;
      authenticate_ = other.authenticate_ != null ? other.authenticate_.Clone() : null;
      authUserAdd_ = other.authUserAdd_ != null ? other.authUserAdd_.Clone() : null;
      authUserDelete_ = other.authUserDelete_ != null ? other.authUserDelete_.Clone() : null;
      authUserGet_ = other.authUserGet_ != null ? other.authUserGet_.Clone() : null;
      authUserChangePassword_ = other.authUserChangePassword_ != null ? other.authUserChangePassword_.Clone() : null;
      authUserGrantRole_ = other.authUserGrantRole_ != null ? other.authUserGrantRole_.Clone() : null;
      authUserRevokeRole_ = other.authUserRevokeRole_ != null ? other.authUserRevokeRole_.Clone() : null;
      authUserList_ = other.authUserList_ != null ? other.authUserList_.Clone() : null;
      authRoleList_ = other.authRoleList_ != null ? other.authRoleList_.Clone() : null;
      authRoleAdd_ = other.authRoleAdd_ != null ? other.authRoleAdd_.Clone() : null;
      authRoleDelete_ = other.authRoleDelete_ != null ? other.authRoleDelete_.Clone() : null;
      authRoleGet_ = other.authRoleGet_ != null ? other.authRoleGet_.Clone() : null;
      authRoleGrantPermission_ = other.authRoleGrantPermission_ != null ? other.authRoleGrantPermission_.Clone() : null;
      authRoleRevokePermission_ = other.authRoleRevokePermission_ != null ? other.authRoleRevokePermission_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InternalRaftRequest Clone() {
      return new InternalRaftRequest(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 100;
    private global::Etcdserverpb.RequestHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.RequestHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private ulong iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "v2" field.</summary>
    public const int V2FieldNumber = 2;
    private global::Etcdserverpb.Request v2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.Request V2 {
      get { return v2_; }
      set {
        v2_ = value;
      }
    }

    /// <summary>Field number for the "range" field.</summary>
    public const int RangeFieldNumber = 3;
    private global::Etcdserverpb.RangeRequest range_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.RangeRequest Range {
      get { return range_; }
      set {
        range_ = value;
      }
    }

    /// <summary>Field number for the "put" field.</summary>
    public const int PutFieldNumber = 4;
    private global::Etcdserverpb.PutRequest put_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.PutRequest Put {
      get { return put_; }
      set {
        put_ = value;
      }
    }

    /// <summary>Field number for the "delete_range" field.</summary>
    public const int DeleteRangeFieldNumber = 5;
    private global::Etcdserverpb.DeleteRangeRequest deleteRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.DeleteRangeRequest DeleteRange {
      get { return deleteRange_; }
      set {
        deleteRange_ = value;
      }
    }

    /// <summary>Field number for the "txn" field.</summary>
    public const int TxnFieldNumber = 6;
    private global::Etcdserverpb.TxnRequest txn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.TxnRequest Txn {
      get { return txn_; }
      set {
        txn_ = value;
      }
    }

    /// <summary>Field number for the "compaction" field.</summary>
    public const int CompactionFieldNumber = 7;
    private global::Etcdserverpb.CompactionRequest compaction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.CompactionRequest Compaction {
      get { return compaction_; }
      set {
        compaction_ = value;
      }
    }

    /// <summary>Field number for the "lease_grant" field.</summary>
    public const int LeaseGrantFieldNumber = 8;
    private global::Etcdserverpb.LeaseGrantRequest leaseGrant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.LeaseGrantRequest LeaseGrant {
      get { return leaseGrant_; }
      set {
        leaseGrant_ = value;
      }
    }

    /// <summary>Field number for the "lease_revoke" field.</summary>
    public const int LeaseRevokeFieldNumber = 9;
    private global::Etcdserverpb.LeaseRevokeRequest leaseRevoke_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.LeaseRevokeRequest LeaseRevoke {
      get { return leaseRevoke_; }
      set {
        leaseRevoke_ = value;
      }
    }

    /// <summary>Field number for the "alarm" field.</summary>
    public const int AlarmFieldNumber = 10;
    private global::Etcdserverpb.AlarmRequest alarm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AlarmRequest Alarm {
      get { return alarm_; }
      set {
        alarm_ = value;
      }
    }

    /// <summary>Field number for the "lease_checkpoint" field.</summary>
    public const int LeaseCheckpointFieldNumber = 11;
    private global::Etcdserverpb.LeaseCheckpointRequest leaseCheckpoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.LeaseCheckpointRequest LeaseCheckpoint {
      get { return leaseCheckpoint_; }
      set {
        leaseCheckpoint_ = value;
      }
    }

    /// <summary>Field number for the "auth_enable" field.</summary>
    public const int AuthEnableFieldNumber = 1000;
    private global::Etcdserverpb.AuthEnableRequest authEnable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthEnableRequest AuthEnable {
      get { return authEnable_; }
      set {
        authEnable_ = value;
      }
    }

    /// <summary>Field number for the "auth_disable" field.</summary>
    public const int AuthDisableFieldNumber = 1011;
    private global::Etcdserverpb.AuthDisableRequest authDisable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthDisableRequest AuthDisable {
      get { return authDisable_; }
      set {
        authDisable_ = value;
      }
    }

    /// <summary>Field number for the "authenticate" field.</summary>
    public const int AuthenticateFieldNumber = 1012;
    private global::Etcdserverpb.InternalAuthenticateRequest authenticate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.InternalAuthenticateRequest Authenticate {
      get { return authenticate_; }
      set {
        authenticate_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_add" field.</summary>
    public const int AuthUserAddFieldNumber = 1100;
    private global::Etcdserverpb.AuthUserAddRequest authUserAdd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserAddRequest AuthUserAdd {
      get { return authUserAdd_; }
      set {
        authUserAdd_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_delete" field.</summary>
    public const int AuthUserDeleteFieldNumber = 1101;
    private global::Etcdserverpb.AuthUserDeleteRequest authUserDelete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserDeleteRequest AuthUserDelete {
      get { return authUserDelete_; }
      set {
        authUserDelete_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_get" field.</summary>
    public const int AuthUserGetFieldNumber = 1102;
    private global::Etcdserverpb.AuthUserGetRequest authUserGet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserGetRequest AuthUserGet {
      get { return authUserGet_; }
      set {
        authUserGet_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_change_password" field.</summary>
    public const int AuthUserChangePasswordFieldNumber = 1103;
    private global::Etcdserverpb.AuthUserChangePasswordRequest authUserChangePassword_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserChangePasswordRequest AuthUserChangePassword {
      get { return authUserChangePassword_; }
      set {
        authUserChangePassword_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_grant_role" field.</summary>
    public const int AuthUserGrantRoleFieldNumber = 1104;
    private global::Etcdserverpb.AuthUserGrantRoleRequest authUserGrantRole_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserGrantRoleRequest AuthUserGrantRole {
      get { return authUserGrantRole_; }
      set {
        authUserGrantRole_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_revoke_role" field.</summary>
    public const int AuthUserRevokeRoleFieldNumber = 1105;
    private global::Etcdserverpb.AuthUserRevokeRoleRequest authUserRevokeRole_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserRevokeRoleRequest AuthUserRevokeRole {
      get { return authUserRevokeRole_; }
      set {
        authUserRevokeRole_ = value;
      }
    }

    /// <summary>Field number for the "auth_user_list" field.</summary>
    public const int AuthUserListFieldNumber = 1106;
    private global::Etcdserverpb.AuthUserListRequest authUserList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthUserListRequest AuthUserList {
      get { return authUserList_; }
      set {
        authUserList_ = value;
      }
    }

    /// <summary>Field number for the "auth_role_list" field.</summary>
    public const int AuthRoleListFieldNumber = 1107;
    private global::Etcdserverpb.AuthRoleListRequest authRoleList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthRoleListRequest AuthRoleList {
      get { return authRoleList_; }
      set {
        authRoleList_ = value;
      }
    }

    /// <summary>Field number for the "auth_role_add" field.</summary>
    public const int AuthRoleAddFieldNumber = 1200;
    private global::Etcdserverpb.AuthRoleAddRequest authRoleAdd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthRoleAddRequest AuthRoleAdd {
      get { return authRoleAdd_; }
      set {
        authRoleAdd_ = value;
      }
    }

    /// <summary>Field number for the "auth_role_delete" field.</summary>
    public const int AuthRoleDeleteFieldNumber = 1201;
    private global::Etcdserverpb.AuthRoleDeleteRequest authRoleDelete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthRoleDeleteRequest AuthRoleDelete {
      get { return authRoleDelete_; }
      set {
        authRoleDelete_ = value;
      }
    }

    /// <summary>Field number for the "auth_role_get" field.</summary>
    public const int AuthRoleGetFieldNumber = 1202;
    private global::Etcdserverpb.AuthRoleGetRequest authRoleGet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthRoleGetRequest AuthRoleGet {
      get { return authRoleGet_; }
      set {
        authRoleGet_ = value;
      }
    }

    /// <summary>Field number for the "auth_role_grant_permission" field.</summary>
    public const int AuthRoleGrantPermissionFieldNumber = 1203;
    private global::Etcdserverpb.AuthRoleGrantPermissionRequest authRoleGrantPermission_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthRoleGrantPermissionRequest AuthRoleGrantPermission {
      get { return authRoleGrantPermission_; }
      set {
        authRoleGrantPermission_ = value;
      }
    }

    /// <summary>Field number for the "auth_role_revoke_permission" field.</summary>
    public const int AuthRoleRevokePermissionFieldNumber = 1204;
    private global::Etcdserverpb.AuthRoleRevokePermissionRequest authRoleRevokePermission_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Etcdserverpb.AuthRoleRevokePermissionRequest AuthRoleRevokePermission {
      get { return authRoleRevokePermission_; }
      set {
        authRoleRevokePermission_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InternalRaftRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InternalRaftRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (ID != other.ID) return false;
      if (!object.Equals(V2, other.V2)) return false;
      if (!object.Equals(Range, other.Range)) return false;
      if (!object.Equals(Put, other.Put)) return false;
      if (!object.Equals(DeleteRange, other.DeleteRange)) return false;
      if (!object.Equals(Txn, other.Txn)) return false;
      if (!object.Equals(Compaction, other.Compaction)) return false;
      if (!object.Equals(LeaseGrant, other.LeaseGrant)) return false;
      if (!object.Equals(LeaseRevoke, other.LeaseRevoke)) return false;
      if (!object.Equals(Alarm, other.Alarm)) return false;
      if (!object.Equals(LeaseCheckpoint, other.LeaseCheckpoint)) return false;
      if (!object.Equals(AuthEnable, other.AuthEnable)) return false;
      if (!object.Equals(AuthDisable, other.AuthDisable)) return false;
      if (!object.Equals(Authenticate, other.Authenticate)) return false;
      if (!object.Equals(AuthUserAdd, other.AuthUserAdd)) return false;
      if (!object.Equals(AuthUserDelete, other.AuthUserDelete)) return false;
      if (!object.Equals(AuthUserGet, other.AuthUserGet)) return false;
      if (!object.Equals(AuthUserChangePassword, other.AuthUserChangePassword)) return false;
      if (!object.Equals(AuthUserGrantRole, other.AuthUserGrantRole)) return false;
      if (!object.Equals(AuthUserRevokeRole, other.AuthUserRevokeRole)) return false;
      if (!object.Equals(AuthUserList, other.AuthUserList)) return false;
      if (!object.Equals(AuthRoleList, other.AuthRoleList)) return false;
      if (!object.Equals(AuthRoleAdd, other.AuthRoleAdd)) return false;
      if (!object.Equals(AuthRoleDelete, other.AuthRoleDelete)) return false;
      if (!object.Equals(AuthRoleGet, other.AuthRoleGet)) return false;
      if (!object.Equals(AuthRoleGrantPermission, other.AuthRoleGrantPermission)) return false;
      if (!object.Equals(AuthRoleRevokePermission, other.AuthRoleRevokePermission)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (ID != 0UL) hash ^= ID.GetHashCode();
      if (v2_ != null) hash ^= V2.GetHashCode();
      if (range_ != null) hash ^= Range.GetHashCode();
      if (put_ != null) hash ^= Put.GetHashCode();
      if (deleteRange_ != null) hash ^= DeleteRange.GetHashCode();
      if (txn_ != null) hash ^= Txn.GetHashCode();
      if (compaction_ != null) hash ^= Compaction.GetHashCode();
      if (leaseGrant_ != null) hash ^= LeaseGrant.GetHashCode();
      if (leaseRevoke_ != null) hash ^= LeaseRevoke.GetHashCode();
      if (alarm_ != null) hash ^= Alarm.GetHashCode();
      if (leaseCheckpoint_ != null) hash ^= LeaseCheckpoint.GetHashCode();
      if (authEnable_ != null) hash ^= AuthEnable.GetHashCode();
      if (authDisable_ != null) hash ^= AuthDisable.GetHashCode();
      if (authenticate_ != null) hash ^= Authenticate.GetHashCode();
      if (authUserAdd_ != null) hash ^= AuthUserAdd.GetHashCode();
      if (authUserDelete_ != null) hash ^= AuthUserDelete.GetHashCode();
      if (authUserGet_ != null) hash ^= AuthUserGet.GetHashCode();
      if (authUserChangePassword_ != null) hash ^= AuthUserChangePassword.GetHashCode();
      if (authUserGrantRole_ != null) hash ^= AuthUserGrantRole.GetHashCode();
      if (authUserRevokeRole_ != null) hash ^= AuthUserRevokeRole.GetHashCode();
      if (authUserList_ != null) hash ^= AuthUserList.GetHashCode();
      if (authRoleList_ != null) hash ^= AuthRoleList.GetHashCode();
      if (authRoleAdd_ != null) hash ^= AuthRoleAdd.GetHashCode();
      if (authRoleDelete_ != null) hash ^= AuthRoleDelete.GetHashCode();
      if (authRoleGet_ != null) hash ^= AuthRoleGet.GetHashCode();
      if (authRoleGrantPermission_ != null) hash ^= AuthRoleGrantPermission.GetHashCode();
      if (authRoleRevokePermission_ != null) hash ^= AuthRoleRevokePermission.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ID != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ID);
      }
      if (v2_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(V2);
      }
      if (range_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Range);
      }
      if (put_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Put);
      }
      if (deleteRange_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(DeleteRange);
      }
      if (txn_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Txn);
      }
      if (compaction_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Compaction);
      }
      if (leaseGrant_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(LeaseGrant);
      }
      if (leaseRevoke_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(LeaseRevoke);
      }
      if (alarm_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Alarm);
      }
      if (leaseCheckpoint_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(LeaseCheckpoint);
      }
      if (header_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Header);
      }
      if (authEnable_ != null) {
        output.WriteRawTag(194, 62);
        output.WriteMessage(AuthEnable);
      }
      if (authDisable_ != null) {
        output.WriteRawTag(154, 63);
        output.WriteMessage(AuthDisable);
      }
      if (authenticate_ != null) {
        output.WriteRawTag(162, 63);
        output.WriteMessage(Authenticate);
      }
      if (authUserAdd_ != null) {
        output.WriteRawTag(226, 68);
        output.WriteMessage(AuthUserAdd);
      }
      if (authUserDelete_ != null) {
        output.WriteRawTag(234, 68);
        output.WriteMessage(AuthUserDelete);
      }
      if (authUserGet_ != null) {
        output.WriteRawTag(242, 68);
        output.WriteMessage(AuthUserGet);
      }
      if (authUserChangePassword_ != null) {
        output.WriteRawTag(250, 68);
        output.WriteMessage(AuthUserChangePassword);
      }
      if (authUserGrantRole_ != null) {
        output.WriteRawTag(130, 69);
        output.WriteMessage(AuthUserGrantRole);
      }
      if (authUserRevokeRole_ != null) {
        output.WriteRawTag(138, 69);
        output.WriteMessage(AuthUserRevokeRole);
      }
      if (authUserList_ != null) {
        output.WriteRawTag(146, 69);
        output.WriteMessage(AuthUserList);
      }
      if (authRoleList_ != null) {
        output.WriteRawTag(154, 69);
        output.WriteMessage(AuthRoleList);
      }
      if (authRoleAdd_ != null) {
        output.WriteRawTag(130, 75);
        output.WriteMessage(AuthRoleAdd);
      }
      if (authRoleDelete_ != null) {
        output.WriteRawTag(138, 75);
        output.WriteMessage(AuthRoleDelete);
      }
      if (authRoleGet_ != null) {
        output.WriteRawTag(146, 75);
        output.WriteMessage(AuthRoleGet);
      }
      if (authRoleGrantPermission_ != null) {
        output.WriteRawTag(154, 75);
        output.WriteMessage(AuthRoleGrantPermission);
      }
      if (authRoleRevokePermission_ != null) {
        output.WriteRawTag(162, 75);
        output.WriteMessage(AuthRoleRevokePermission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (ID != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ID);
      }
      if (v2_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(V2);
      }
      if (range_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Range);
      }
      if (put_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Put);
      }
      if (deleteRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteRange);
      }
      if (txn_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Txn);
      }
      if (compaction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Compaction);
      }
      if (leaseGrant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaseGrant);
      }
      if (leaseRevoke_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaseRevoke);
      }
      if (alarm_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Alarm);
      }
      if (leaseCheckpoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaseCheckpoint);
      }
      if (authEnable_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthEnable);
      }
      if (authDisable_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthDisable);
      }
      if (authenticate_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Authenticate);
      }
      if (authUserAdd_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserAdd);
      }
      if (authUserDelete_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserDelete);
      }
      if (authUserGet_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserGet);
      }
      if (authUserChangePassword_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserChangePassword);
      }
      if (authUserGrantRole_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserGrantRole);
      }
      if (authUserRevokeRole_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserRevokeRole);
      }
      if (authUserList_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthUserList);
      }
      if (authRoleList_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthRoleList);
      }
      if (authRoleAdd_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthRoleAdd);
      }
      if (authRoleDelete_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthRoleDelete);
      }
      if (authRoleGet_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthRoleGet);
      }
      if (authRoleGrantPermission_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthRoleGrantPermission);
      }
      if (authRoleRevokePermission_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AuthRoleRevokePermission);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InternalRaftRequest other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Etcdserverpb.RequestHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.ID != 0UL) {
        ID = other.ID;
      }
      if (other.v2_ != null) {
        if (v2_ == null) {
          V2 = new global::Etcdserverpb.Request();
        }
        V2.MergeFrom(other.V2);
      }
      if (other.range_ != null) {
        if (range_ == null) {
          Range = new global::Etcdserverpb.RangeRequest();
        }
        Range.MergeFrom(other.Range);
      }
      if (other.put_ != null) {
        if (put_ == null) {
          Put = new global::Etcdserverpb.PutRequest();
        }
        Put.MergeFrom(other.Put);
      }
      if (other.deleteRange_ != null) {
        if (deleteRange_ == null) {
          DeleteRange = new global::Etcdserverpb.DeleteRangeRequest();
        }
        DeleteRange.MergeFrom(other.DeleteRange);
      }
      if (other.txn_ != null) {
        if (txn_ == null) {
          Txn = new global::Etcdserverpb.TxnRequest();
        }
        Txn.MergeFrom(other.Txn);
      }
      if (other.compaction_ != null) {
        if (compaction_ == null) {
          Compaction = new global::Etcdserverpb.CompactionRequest();
        }
        Compaction.MergeFrom(other.Compaction);
      }
      if (other.leaseGrant_ != null) {
        if (leaseGrant_ == null) {
          LeaseGrant = new global::Etcdserverpb.LeaseGrantRequest();
        }
        LeaseGrant.MergeFrom(other.LeaseGrant);
      }
      if (other.leaseRevoke_ != null) {
        if (leaseRevoke_ == null) {
          LeaseRevoke = new global::Etcdserverpb.LeaseRevokeRequest();
        }
        LeaseRevoke.MergeFrom(other.LeaseRevoke);
      }
      if (other.alarm_ != null) {
        if (alarm_ == null) {
          Alarm = new global::Etcdserverpb.AlarmRequest();
        }
        Alarm.MergeFrom(other.Alarm);
      }
      if (other.leaseCheckpoint_ != null) {
        if (leaseCheckpoint_ == null) {
          LeaseCheckpoint = new global::Etcdserverpb.LeaseCheckpointRequest();
        }
        LeaseCheckpoint.MergeFrom(other.LeaseCheckpoint);
      }
      if (other.authEnable_ != null) {
        if (authEnable_ == null) {
          AuthEnable = new global::Etcdserverpb.AuthEnableRequest();
        }
        AuthEnable.MergeFrom(other.AuthEnable);
      }
      if (other.authDisable_ != null) {
        if (authDisable_ == null) {
          AuthDisable = new global::Etcdserverpb.AuthDisableRequest();
        }
        AuthDisable.MergeFrom(other.AuthDisable);
      }
      if (other.authenticate_ != null) {
        if (authenticate_ == null) {
          Authenticate = new global::Etcdserverpb.InternalAuthenticateRequest();
        }
        Authenticate.MergeFrom(other.Authenticate);
      }
      if (other.authUserAdd_ != null) {
        if (authUserAdd_ == null) {
          AuthUserAdd = new global::Etcdserverpb.AuthUserAddRequest();
        }
        AuthUserAdd.MergeFrom(other.AuthUserAdd);
      }
      if (other.authUserDelete_ != null) {
        if (authUserDelete_ == null) {
          AuthUserDelete = new global::Etcdserverpb.AuthUserDeleteRequest();
        }
        AuthUserDelete.MergeFrom(other.AuthUserDelete);
      }
      if (other.authUserGet_ != null) {
        if (authUserGet_ == null) {
          AuthUserGet = new global::Etcdserverpb.AuthUserGetRequest();
        }
        AuthUserGet.MergeFrom(other.AuthUserGet);
      }
      if (other.authUserChangePassword_ != null) {
        if (authUserChangePassword_ == null) {
          AuthUserChangePassword = new global::Etcdserverpb.AuthUserChangePasswordRequest();
        }
        AuthUserChangePassword.MergeFrom(other.AuthUserChangePassword);
      }
      if (other.authUserGrantRole_ != null) {
        if (authUserGrantRole_ == null) {
          AuthUserGrantRole = new global::Etcdserverpb.AuthUserGrantRoleRequest();
        }
        AuthUserGrantRole.MergeFrom(other.AuthUserGrantRole);
      }
      if (other.authUserRevokeRole_ != null) {
        if (authUserRevokeRole_ == null) {
          AuthUserRevokeRole = new global::Etcdserverpb.AuthUserRevokeRoleRequest();
        }
        AuthUserRevokeRole.MergeFrom(other.AuthUserRevokeRole);
      }
      if (other.authUserList_ != null) {
        if (authUserList_ == null) {
          AuthUserList = new global::Etcdserverpb.AuthUserListRequest();
        }
        AuthUserList.MergeFrom(other.AuthUserList);
      }
      if (other.authRoleList_ != null) {
        if (authRoleList_ == null) {
          AuthRoleList = new global::Etcdserverpb.AuthRoleListRequest();
        }
        AuthRoleList.MergeFrom(other.AuthRoleList);
      }
      if (other.authRoleAdd_ != null) {
        if (authRoleAdd_ == null) {
          AuthRoleAdd = new global::Etcdserverpb.AuthRoleAddRequest();
        }
        AuthRoleAdd.MergeFrom(other.AuthRoleAdd);
      }
      if (other.authRoleDelete_ != null) {
        if (authRoleDelete_ == null) {
          AuthRoleDelete = new global::Etcdserverpb.AuthRoleDeleteRequest();
        }
        AuthRoleDelete.MergeFrom(other.AuthRoleDelete);
      }
      if (other.authRoleGet_ != null) {
        if (authRoleGet_ == null) {
          AuthRoleGet = new global::Etcdserverpb.AuthRoleGetRequest();
        }
        AuthRoleGet.MergeFrom(other.AuthRoleGet);
      }
      if (other.authRoleGrantPermission_ != null) {
        if (authRoleGrantPermission_ == null) {
          AuthRoleGrantPermission = new global::Etcdserverpb.AuthRoleGrantPermissionRequest();
        }
        AuthRoleGrantPermission.MergeFrom(other.AuthRoleGrantPermission);
      }
      if (other.authRoleRevokePermission_ != null) {
        if (authRoleRevokePermission_ == null) {
          AuthRoleRevokePermission = new global::Etcdserverpb.AuthRoleRevokePermissionRequest();
        }
        AuthRoleRevokePermission.MergeFrom(other.AuthRoleRevokePermission);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadUInt64();
            break;
          }
          case 18: {
            if (v2_ == null) {
              V2 = new global::Etcdserverpb.Request();
            }
            input.ReadMessage(V2);
            break;
          }
          case 26: {
            if (range_ == null) {
              Range = new global::Etcdserverpb.RangeRequest();
            }
            input.ReadMessage(Range);
            break;
          }
          case 34: {
            if (put_ == null) {
              Put = new global::Etcdserverpb.PutRequest();
            }
            input.ReadMessage(Put);
            break;
          }
          case 42: {
            if (deleteRange_ == null) {
              DeleteRange = new global::Etcdserverpb.DeleteRangeRequest();
            }
            input.ReadMessage(DeleteRange);
            break;
          }
          case 50: {
            if (txn_ == null) {
              Txn = new global::Etcdserverpb.TxnRequest();
            }
            input.ReadMessage(Txn);
            break;
          }
          case 58: {
            if (compaction_ == null) {
              Compaction = new global::Etcdserverpb.CompactionRequest();
            }
            input.ReadMessage(Compaction);
            break;
          }
          case 66: {
            if (leaseGrant_ == null) {
              LeaseGrant = new global::Etcdserverpb.LeaseGrantRequest();
            }
            input.ReadMessage(LeaseGrant);
            break;
          }
          case 74: {
            if (leaseRevoke_ == null) {
              LeaseRevoke = new global::Etcdserverpb.LeaseRevokeRequest();
            }
            input.ReadMessage(LeaseRevoke);
            break;
          }
          case 82: {
            if (alarm_ == null) {
              Alarm = new global::Etcdserverpb.AlarmRequest();
            }
            input.ReadMessage(Alarm);
            break;
          }
          case 90: {
            if (leaseCheckpoint_ == null) {
              LeaseCheckpoint = new global::Etcdserverpb.LeaseCheckpointRequest();
            }
            input.ReadMessage(LeaseCheckpoint);
            break;
          }
          case 802: {
            if (header_ == null) {
              Header = new global::Etcdserverpb.RequestHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 8002: {
            if (authEnable_ == null) {
              AuthEnable = new global::Etcdserverpb.AuthEnableRequest();
            }
            input.ReadMessage(AuthEnable);
            break;
          }
          case 8090: {
            if (authDisable_ == null) {
              AuthDisable = new global::Etcdserverpb.AuthDisableRequest();
            }
            input.ReadMessage(AuthDisable);
            break;
          }
          case 8098: {
            if (authenticate_ == null) {
              Authenticate = new global::Etcdserverpb.InternalAuthenticateRequest();
            }
            input.ReadMessage(Authenticate);
            break;
          }
          case 8802: {
            if (authUserAdd_ == null) {
              AuthUserAdd = new global::Etcdserverpb.AuthUserAddRequest();
            }
            input.ReadMessage(AuthUserAdd);
            break;
          }
          case 8810: {
            if (authUserDelete_ == null) {
              AuthUserDelete = new global::Etcdserverpb.AuthUserDeleteRequest();
            }
            input.ReadMessage(AuthUserDelete);
            break;
          }
          case 8818: {
            if (authUserGet_ == null) {
              AuthUserGet = new global::Etcdserverpb.AuthUserGetRequest();
            }
            input.ReadMessage(AuthUserGet);
            break;
          }
          case 8826: {
            if (authUserChangePassword_ == null) {
              AuthUserChangePassword = new global::Etcdserverpb.AuthUserChangePasswordRequest();
            }
            input.ReadMessage(AuthUserChangePassword);
            break;
          }
          case 8834: {
            if (authUserGrantRole_ == null) {
              AuthUserGrantRole = new global::Etcdserverpb.AuthUserGrantRoleRequest();
            }
            input.ReadMessage(AuthUserGrantRole);
            break;
          }
          case 8842: {
            if (authUserRevokeRole_ == null) {
              AuthUserRevokeRole = new global::Etcdserverpb.AuthUserRevokeRoleRequest();
            }
            input.ReadMessage(AuthUserRevokeRole);
            break;
          }
          case 8850: {
            if (authUserList_ == null) {
              AuthUserList = new global::Etcdserverpb.AuthUserListRequest();
            }
            input.ReadMessage(AuthUserList);
            break;
          }
          case 8858: {
            if (authRoleList_ == null) {
              AuthRoleList = new global::Etcdserverpb.AuthRoleListRequest();
            }
            input.ReadMessage(AuthRoleList);
            break;
          }
          case 9602: {
            if (authRoleAdd_ == null) {
              AuthRoleAdd = new global::Etcdserverpb.AuthRoleAddRequest();
            }
            input.ReadMessage(AuthRoleAdd);
            break;
          }
          case 9610: {
            if (authRoleDelete_ == null) {
              AuthRoleDelete = new global::Etcdserverpb.AuthRoleDeleteRequest();
            }
            input.ReadMessage(AuthRoleDelete);
            break;
          }
          case 9618: {
            if (authRoleGet_ == null) {
              AuthRoleGet = new global::Etcdserverpb.AuthRoleGetRequest();
            }
            input.ReadMessage(AuthRoleGet);
            break;
          }
          case 9626: {
            if (authRoleGrantPermission_ == null) {
              AuthRoleGrantPermission = new global::Etcdserverpb.AuthRoleGrantPermissionRequest();
            }
            input.ReadMessage(AuthRoleGrantPermission);
            break;
          }
          case 9634: {
            if (authRoleRevokePermission_ == null) {
              AuthRoleRevokePermission = new global::Etcdserverpb.AuthRoleRevokePermissionRequest();
            }
            input.ReadMessage(AuthRoleRevokePermission);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EmptyResponse : pb::IMessage<EmptyResponse> {
    private static readonly pb::MessageParser<EmptyResponse> _parser = new pb::MessageParser<EmptyResponse>(() => new EmptyResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmptyResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etcdserverpb.RaftInternalReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmptyResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmptyResponse(EmptyResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmptyResponse Clone() {
      return new EmptyResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmptyResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmptyResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmptyResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  /// <summary>
  /// What is the difference between AuthenticateRequest (defined in rpc.proto) and InternalAuthenticateRequest?
  /// InternalAuthenticateRequest has a member that is filled by etcdserver and shouldn't be user-facing.
  /// For avoiding misusage the field, we have an internal version of AuthenticateRequest.
  /// </summary>
  public sealed partial class InternalAuthenticateRequest : pb::IMessage<InternalAuthenticateRequest> {
    private static readonly pb::MessageParser<InternalAuthenticateRequest> _parser = new pb::MessageParser<InternalAuthenticateRequest>(() => new InternalAuthenticateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InternalAuthenticateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etcdserverpb.RaftInternalReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InternalAuthenticateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InternalAuthenticateRequest(InternalAuthenticateRequest other) : this() {
      name_ = other.name_;
      password_ = other.password_;
      simpleToken_ = other.simpleToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InternalAuthenticateRequest Clone() {
      return new InternalAuthenticateRequest(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "simple_token" field.</summary>
    public const int SimpleTokenFieldNumber = 3;
    private string simpleToken_ = "";
    /// <summary>
    /// simple_token is generated in API layer (etcdserver/v3_server.go)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SimpleToken {
      get { return simpleToken_; }
      set {
        simpleToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InternalAuthenticateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InternalAuthenticateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      if (SimpleToken != other.SimpleToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (SimpleToken.Length != 0) hash ^= SimpleToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (SimpleToken.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SimpleToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (SimpleToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SimpleToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InternalAuthenticateRequest other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.SimpleToken.Length != 0) {
        SimpleToken = other.SimpleToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            SimpleToken = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
